// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHDIqNL9D6ctPBAXhDPSi-vbs6CtpWKKQ',
    appId: '1:731779843746:web:d605af0f4d96a611d479fb',
    messagingSenderId: '731779843746',
    projectId: 'budgetplanner-bce2b',
    authDomain: 'budgetplanner-bce2b.firebaseapp.com',
    storageBucket: 'budgetplanner-bce2b.firebasestorage.app',
    measurementId: 'G-WNJV5NMC8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGVO-BS3Dum059dI2BVYbtG6HAIdOZcgU',
    appId: '1:731779843746:android:a262a20cad0f0905d479fb',
    messagingSenderId: '731779843746',
    projectId: 'budgetplanner-bce2b',
    storageBucket: 'budgetplanner-bce2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDED5-HZMWrv0dwGAMmM8dNdya-cMdAzuI',
    appId: '1:731779843746:ios:13254edd80efa2c4d479fb',
    messagingSenderId: '731779843746',
    projectId: 'budgetplanner-bce2b',
    storageBucket: 'budgetplanner-bce2b.firebasestorage.app',
    iosBundleId: 'com.example.budgetPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDED5-HZMWrv0dwGAMmM8dNdya-cMdAzuI',
    appId: '1:731779843746:ios:13254edd80efa2c4d479fb',
    messagingSenderId: '731779843746',
    projectId: 'budgetplanner-bce2b',
    storageBucket: 'budgetplanner-bce2b.firebasestorage.app',
    iosBundleId: 'com.example.budgetPlanner',
  );
}
